### ISSUE TITLE
Translations English + Swedish

### ISSUE THREAD

**Issue by LB22** [artoh/kitupiikki#1285]
Hi there! What an awesome project. I see it's constantly improved too. Great work! 

I am riikinruotsalainen living in Finland and so Kitsas might suit me very well to help me run my business here. 

I'd like to help translate this to both English and Swedish as I personally like to switch between both languages. I don't speak any Finnish which makes my help very limited, as all code is also in Finnish, but I'm sure there is something I can do.

I noticed a few missing translations running the program in Swedish and I'd like to help fix them. I saw in the source code there are some .json file with translations, but perhaps not all written text have a corresponding key? i.e, maybe some hardcoded finnish text needs to be moved so that it can be translated and used dynamically?

The best way for me to help is translating between English and Swedish and correcting sentences/words. Just point me to where.

Edit: Also the website could use translating

I'm running the **portable** version (4.0.2) in "training mode" without root access.
Some pictures of missing translations:

![kitsas1](https://user-images.githubusercontent.com/55314315/216049119-b2d4face-681c-4183-bdce-b6742eef6f23.PNG)
![kitsas2](https://user-images.githubusercontent.com/55314315/216049125-98644059-b233-42dd-9313-31350692e2f8.PNG)
![kitsas4](https://user-images.githubusercontent.com/55314315/216049127-87acceab-9d09-48b8-a2f4-7ca0c5c17b66.PNG)
![kitsas5](https://user-images.githubusercontent.com/55314315/216049129-a0f76c51-9352-4acc-8735-fc4f75017859.PNG)

This seems to happen only when setting up Kitsas the first time, perhaps a bug?
![kitsas6](https://user-images.githubusercontent.com/55314315/216049132-b4200ac0-3921-4b77-a576-d98b3f0f23db.PNG)

File name translation?
![kitsas7](https://user-images.githubusercontent.com/55314315/216049135-b4c2beb5-8064-44d9-bfde-5f7c82f41d7c.PNG)

**Comment by deanc** [comment]
I'd also like to help translate to English. @artoh Could you provide some guidance on where to start?

**Comment by LatroM69** [comment]
> I'd also like to help translate to English. @artoh Could you provide some guidance on where to start? I found the english translation file - should I just slowly work through it?

Hi there! Just checking in—did you make any progress with this? I’m a student in Finland and don’t speak any Finnish/Swedish , but I’d really love to use this software in English.

**Comment by deanc** [comment]
No. Little point in contributing unless the author is willing to engage on the topic. It'd be a substantial amount of effort to get this over the line, and I'd like to know the work is welcomed and supported.

**Comment by LatroM69** [comment]
Fair point. Let’s hope the author engages soon.

**Comment by artoh** [comment]
Hello!

Our original Swedish translation is written by accounting teacher of Praktikum Yrkeskolan. There is some missing strings and maintaining the translation is not so fast as new features (and UI new strings) are published. 

There are about 3000 strings to translate in the user interface. We use Qt Framework and Qt Linquist Tool can be used to edit kitsas/tr/kitsas_sv.ts and kitsas/tr/kitsas_en.ts files (and we will welcome any PR).

tulkki.csv file contains about 350 strings (invoicing, reporting etc. things where any supported language can be selected instead of UI language), tulkki.json is generated based on this csv.

In addition, every Chart of Account (tilikartta) contains lots of strings:  names of accounts, reports and formula for the closing the accounts document (tilinpäätös) . Source files are in the json format.

Our documentation on the web is quite large, about 300 pages and lots of screenshots.

At this moment we have no time to translate all the stuff to English. Of course we will gladly merge any PR containing all the language stuff if somebody has time to make the translation.


Regards,

Arto

**Comment by LatroM69** [comment]
Thank you for your work Kamzil!

**Comment by andrewwippler** [comment]
I am proofing and updating the English strings. I can submit a PR for the application in 3-4 months. You can follow my progress here: https://github.com/andrewwippler/kitsas/tree/english-translations
